apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: alexan757/mysql:5.7
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                 name: secret
                 key: username 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: secret
                 key: password 

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

